#:schema node_modules/wrangler/config-schema.json
name = "email"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "EMAIL_DB"
database_name = "email"
database_id = "915992a2-0a05-4435-b5e0-e4394c9613fd"

[[r2_buckets]]
binding = "EMAIL_BUCKET"
bucket_name = "email"
